version: '3'

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana: 
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana01
    ports:
      - 5601:5601
    networks:
      - elastic

  # my node.js app, which tests if Elasticsearch is running using http://<host>:9200 and sends response to http://<host>:8080
  # Pre-requisite: build the node.js image first
  app:
    image: purplebugs/my_node_http_app:1.0
    ports:
      - 8080:8080
    networks:
      - elastic